### ISSUE TITLE
WebAuthn Self-Registration Question

### ISSUE THREAD

**Issue by klpo-mt** [neos-sdi/adfsmfa#106]
Hi,

we are currently evaluating your solution for use with YubiKeys.
It's an essential alternative for us, so thanks a lot for your efforts up front.

Yet we seem to have difficulties configuring it to our needs and hope you can give some guidance.

What we would like to do:
- self-enroll users
- use yubikeys as only means for authenticating

The way we read your documentation, it should be doable with FIDO/WebAuthn without custom extensions.

What we run into:
- We tried disabling all but the Biometrics provider to solely use WebAuthN, but figured out that TOTP cannot be disabled
- No big deal so far, yet in the self-enrollment dialog we always end up in the TOTP enrollment wizard, with no option to switch to enrolling the YubiKey via the biometrics provider

Active providers are TOTP (since mandatory) and Biometrics. Biometrics is configured with an ADDS backend and we can see the needed attributes present and (as expected) so far empty for the user in question. The enrollment dialog first shows the two registration options (authenticator, biometric device), but after proceeding there is only the TOTP enrollment wizard visible/accessible, which we cannot change to the biometrics provider enrollment. The YubiKey was plugged in and we tried with recent browsers (Chrome, Firefox, Edge).

The Biometrics Provider is configured with 
- Enabled=True
- EnrollWizard=True
- ForceWizard=Enabled
- PinRequired=False
- DirectLogin=True
- Timeout=60000
- Drift Tolerance=30000
- ChallengeSize=128
- ServerDomain=company.com
- ServerName=sso
- Origin=https://sso.company.com/ (without /adfs/services/trust suffix [?])
- RequireValidAttestationRoot=False

Any hint what might be going on or what we could try?

Thanks a lot,
Klaus

**Comment by redhook62** [comment]
Hi Klaus,

Thanks for your questions.
Yes, the TOTP provider cannot be deactivated, on the one hand because we consider that it is the most secure method which does not require access to the network (disconnected), the only things that can allow the totp are the registration phase, trust in the TOTP application ... as well as device compliance ...

However, you can deactivate the Wizard TOTP. but it is necessary that the user can have a reliable secondary solution in the hypothesis or for example he will not have his Yubukey.

So, the user can always indicate "I don't have the code" and temporarily choose to use their TOTP application at login.

For the WebAuthN part,
We rely partly on the Anders Bergs component: [FIDO2-net-lib](https://github.com/abergs/fido2-net-lib)
It is imperative that your ADFS servers have Framework 4.7.2 at least for WebAuthN to work, the previous frameworks contain bugs on the cryptography part (CNG), if this version is not installed the Wizard and biometric authentication will not be active.

Then, the problem certainly comes from Yubikeys, the majority of them do not support corporate accounts, any more than online accounts like Azure ...

Then, the problem certainly comes from Yubikeys, the majority of them do not support corporate accounts, any more than online accounts like Azure ...
Only one or two models will be suitable for adfs, versions 4. 
You could first validate biometrics with fingerprint readers from a PC (Windows Hello) and with Android and IOS mobiles.
Also validate the operation with the FIDO-NET-LIB test site -> https://www.passwordless.dev/overview.

Can you tell us which Yubico key models you have selected?

Thank you for your comeback,

@redhook62

**Comment by klpo-mt** [comment]
Hi Redhook,

.NET 4.7.2 has been applied on both instances of ADFS 2016. The model is a YubiKey 5 NFC and it verifies on https://demo.yubico.com as well as your suggested https://www.passwordless.dev/overview.
From the specs at least it supports basically all of version 4 plus FIDO2.

I just tried with a fingerprint reader on Android, but also there the biometrics registration does not appear.
TOTP as secondary option is ok. What we observe there is that we run into an error after the "key creation" button, which unfortunately does leave a trace in the ADFS eventlog.

So surely our setup is off somewhere. Yet from what we can see everything is as per the (great) install guide. Any hints you would still have for us?

Thanks a lot,
Klaus

**Comment by redhook62** [comment]
Hi, @klpo-mt 

I really have a doubt about the Yubikey NFC 5 for corporate accounts. in the past (2/3 months) tests performed with a 5 NFC version refused to work with corporate accounts, but worked very well with public sites (Live, Google, etc.)

But before you must certify to me that the recording for totp code is functional, because if it is not the case, it indicates that the ADFS account cannot write on your ADDS, but only read.
Unlike ADFS which does not need to write in ADDS at all, the "Active Directory" configuration requires it. try to provide (for testing) a "SuperUser" account such as your domain admin.

Once this is functional, reactivate biometrics, and new tests with Windows Hello, Android and the Yubikey NFC 5 key.

_For example, to circumvent these limitations and for testing purposes only, you can create in your active directory a ToplevelName such as hotmail.com, google.com is to assign these domain names to a specific account that can correspond to the initial public domains, and there your NFC 5 key should accept._

Obviously, it is possible to add events in the Windows eventlog, but we are waiting for FIDO-net-lib, a finalized version (2.0), in order to be able to update without too many side effects .

thank you for your feedback

@redhook62

**Comment by klpo-mt** [comment]
Hi @redhook62,

update:
- TOTP works now and indeed it was due to the ad fs group managed service account not having enough permission.
  Can you recommend a minimum-privilege configuration?
- Unfortunately you seem to be right in that the biometrics provider does not do well with a YubiKey 5 NFC.
  I get into the registration wizard and am prompted to enter PIN + tap it, but then run into an error saying the account is invalid.
  However, I currently cannot test whether it is the YubiKey itself or a provider misconfiguration, since the biometrics registration option is not shown on my Android (a fingerprint is registered). Contrary to the desktop.

some observations:
- some settings seem to be lost on a reboot of the federation services
  - chosen template options when CUSTOM is selected
  - whether or not to show some authenticator app links
- The german translation is misleading at times. We weren't able to set the wizard language to english, it seems to always choose the browser's language.
  If it's a matter of just translating a table of English to German strings, contact me and I could help on that.

..and a question:
- is it possible to register two TOTP authenticators for one user? (if so, how do I navigate the wizardry in order to get there)

Also thanks for the update on event logging, that's going to be key for us.

TOTP + Yubico Authenticator + E-mail fallback seems to be a way forward for us.

Thanks a lot,
Klaus

**Comment by redhook62** [comment]
Hi **@klpo-mt** 

For the security of the ADFS service account, in fact, it is not desirable to let it have write and read access on all the accounts of your ADDS forests. 
This is why we have added the possibility of entering a "Super User" account, which is only used for ADDS access. 
Connection information is marked "Secure", soon we will provide support for LDAPS.

- Adfs service account used to access ADDS forests, must have read/write rights on all users properties (or ensure correct access to the properties described in ADDS configuration).
- Adfs service account , is a "Domain Administrator" (not recommended)
- Adfs service account is member of the "Account Operators" group in all forests (suitable), this account cannot create or write attributes of privileged accounts like domain administrators
- Adfs service account is a "Standard User" (recommended), yous must set privileged account credentials in Security management.
Selected account must have the same rights on other forests.

There are pros and cons when using the ADDS configuration, this is a question that is asked to me regularly.
For information, my configuration with ADDS is as follows.
- Adfs service account is a "Standard User", privileged account credentials are set in Security management.
- "Super User" account is a member of "Account Operators" group in all forests.
- ADDS Schema for MFA is our secure extension with attributes marked with CONFIDENTIAL flag.
- Administrators cannot connect via internet access (LAN and VPN only. No MFA required, but certificate or device registration required).

You can also look at the SQL configuration side (For MFA and also for ADFS), of course, you need a SQL Server instance, so significant costs involved.
- Typical SQL Server configuration.
ADFS with SQL Server (SAML antireplay and others), MFA SQL with always encrypted columns (SQL 2016), and Always On configuration for high availability

For biometrics, your configuration seems OK. 
You can try to modify the "Attestation Conveyance" parameter and pass it to None or Indirect. 
You should be able to test on Windows 10 (Windows Hello), Android (Android safetykey) or Apple (FaceID or TouchID) .
The attitude of Yubico is very surprising. 
I know several companies that have backtracked because of the non-support of corporate accounts and cloud accounts like Azure AD.

For languages, the session language is used (asp.Net and first versions of the MFA).
With the evolution of browsers (Edge, Chrome, FireFox, ...) there is the possibility to change the browser language (example French session, Edge in German -> ADFS and MFA -> German). 
This is the default configuration today. 
You can change how it works using the UseOfUserLanguages property. see [UseOfUserLanguages](https://github.com/neos-sdi/adfsmfa/wiki/05-General%20Settings#general-properties-description)

We did not find any gaps concerning German.
However as indicated [here](https://github.com/neos-sdi/adfsmfa/wiki/11-Localization#builtin-languages) German is automatically translated with cognitive Azure services, and depending on the different languages the result is more or less happy.
Surely, having a correct translation interests us, for example the Italian has been transmitted with a translation of application resources, thanks very much **@AlessandroMenti** 
Obviously, we will be happy to integrate these changes as soon as possible.

Last point concerning the registration of the TOTP key on several devices.
It is no longer possible to display the QRCode or the key used to generate the TOTP code more than once. see the [1st issue](https://github.com/neos-sdi/adfsmfa/issues/1)

To share a key, you must ask an administrator, and if you have provided an email, and that sending emails is operational. 
When editing user properties (MMC) there is a "Send By Mail" button. 
The QRCode and the key will be present in the email (Ultra Confidential !!!). You will therefore be able to scan with several devices or share it among several users.

A new version is near, we still have a small problem and tests to perform

Regards

redhook

**Comment by redhook62** [comment]
Done in version 3.0.2007.0
With others evolutions

Regards
