### ISSUE TITLE
Translation Files not updated(?)

### ISSUE THREAD

**Issue by klpo-mt** [neos-sdi/adfsmfa#112]
Hi @redhook62,

Thanks for the really fast integration of PR #108. We only recently got around to trying again and updated to version 3.0.2007.2.
Unfortunately we don't see a change, as if the language files were not updated. Is this by intention, do we need to wipe and reinstall?

Thanks,
Klaus

**Comment by redhook62** [comment]
Hi **@klpo-mt** 

No, no worries for the German translation, no changes in the resources since the July version.
This was for those using an ADDS schema prior to 2016 (version 85) to correct an exception that occurred while checking attributes.
You can update if you want to the August version.
In September, there will be a (technical) upgrade for the webauth part..

Regards

**Comment by klpo-mt** [comment]
Sorry for replying on a closed topic, but there was a misunderstanding I think.
We were applying the July version in expectation that the language strings change as edited, but they didn't.
Coming from an older version, 3.0.2007.1 or below, is there need to manually replace some language resource files?
Thanks!

**Comment by redhook62** [comment]
Hi @klpo-mt 

If you want to update to the latest version, we haven't added or changed any resources for languages.
So an upgrade is possible, but **the German resources were integrated into the binaries in version 3.0.2007.2** using your submissions (PR).
In short, having the German translation (the good translation...) by default requires version 3.0.2007.2 or higher.
Look at : https://github.com/neos-sdi/adfsmfa/releases

Regards

**Comment by klpo-mt** [comment]
Thanks @redhook62, and clear so far. I don't see pressure to move to the latest and greatest version either and that's not what we tried to do. Sorry if I wasn't clear enough on this.

We upgraded from 3.0.2007.1 to 3.0.2007.2, but the german translation has not visibly changed in the UI. Now we're wondering if we missed a step, despite closely following https://github.com/neos-sdi/adfsmfa/wiki/03-UpgradeFromPrevious. Or if some additional manual action is needed to see the effect.

**Comment by redhook62** [comment]
Hi **@klpo-m**t 

No worries for versions, you have to use the upgrade procedure only the binaries change versions. 
Currently **since April, all binaries are version 3.0.**
This will only happen when there is an added or modified functionality.
So for example updating in September should not have an impact. because it will be the version **3.0**.2009.0

When the version does not change (3.0.xxxx.x) you simply have to uninstall the previous version (3.0.2007.x) and deploy the following binaries (3.0.2008.0 or up). for september it should be the version 3.0.2009.0. on this version we will guarantee a simple replacement of the binaries.

In general, when resources are allocated, we try to indicate it, especially for those who have not provided a PR, and which work with "standalone" resource files.

We have integrated your PR well, and know that we are very grateful. 
If you wish, during a change in language resources, we will post an intermediate version. if then you have any comments, we will do what is necessary to take them into account.

Remember that an upgrade procedure would only be necessary when switching from version 3.0.XXXX.X to version 3.1.XXXX.X or version 4.0.XXXX.X

Between us, apart from waiting for a new version of ADFS, there should not be big evolutions.
For the bugs, we will always be present to solve them, and whatever the version.

Regards

**Comment by klpo-mt** [comment]
I see, thanks @redhook62. So I take it a mere installation of the new msi should pretty much do the trick. We'll doublecheck.

**Comment by redhook62** [comment]
@klpo-mt 

Yes, normally no problem.
Otherwise save your configuration in an xml file (Export-MFASystemConfiguration)
and keep your previous MSI file
So you can go back (using Import-MFASystemConfiguration with your previous MSI installed)

Today, we have not the habit, it is very hot in Paris (37/38 degrees), and I apologize for not having been precise enough at the start ...

Regards

**Comment by klpo-mt** [comment]
Just to conclude on this: apparently some cache-timer had to expire somewhere for the new translation to kick in. Before it had survived both incognito modes and adfs instance reboots. Yet at some point the changes appeared.
Thanks for the help!

**Comment by klpo-mt** [comment]
hi @redhook62, sorry to keep going on this ticket. We've enrolled users and it's working well so far.
Yet, for some users still the original german translation from before the update is shown. It's not the biggest of deals, the system is working nonetheless, but it is confusing many users. I can't make out any pattern (browsers, language settings etc.). I myself use firefox and randomly get the "old" german UI as well. Would you have an idea about this? Thanks a lot

**Comment by redhook62** [comment]
Hi **@klpo-mt** 

As mentioned above, your German translations have been integrated into the provided binaries. 
You have to make sure that you have deployed these binaries on each AD FS server (not the proxies).

If, you first used the "manual" translation method with the text files of resources on the server (MFA \ ResourceSet) in program files, you must remove these files, because in this case they take precedence over the translated resources in binaries.

Otherwise, there is no reason for the translations to change on the fly.
In the **general configuration** you can change the **UseOfUserLanguages** property (True = Language defined in the browser, False = Language of the operating system).

Also make sure that the browser does not perform itself translations on the fly...

Regards
