### ISSUE TITLE
User with custom UPN Suffixes can't Authenticate "Invalid Key for User"

### ISSUE THREAD

**Issue by Steven2020-20** [neos-sdi/adfsmfa#117]
Hello Guy's

i ran into an Error when using a Custom created UPN Suffix. 
Maybe  it is a Bug or, maybe thers an Error in the config?:

Details:
Internal DNS-Domain name: company.local 
We added a Custom UPN Suffix: company.com

If the UPN Suffix for the User is set to the Domain Name, e.g. user1@company.local 
The OTP MFA Authentication works as expected.

If the UPN Suffix for the user is set to the Custom UPN, e.g. user1@company.com 
OTP MFA Auth Fails.

The Following is loggend in the Application Log of ADFS Server:
SetAuthenticationResult Error user1@company.com 
 SECURTY ERROR : Invalid Key for User user1@company.com 
    at Neos.IdentityServer.MultiFactor.Common.NeosOTPProvider.CheckPin(AuthenticationContext usercontext, Int32 pin)
   at Neos.IdentityServer.MultiFactor.Common.NeosOTPProvider.SetAuthenticationResult(AuthenticationContext ctx, String pin)
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.SetAuthenticationResult(AuthenticationContext usercontext, String totp, PreferredMethod method)

Can Anybody help?
Regards
Stefan

**Comment by redhook62** [comment]
Hi **@Steven2020-20** 

This seems normal to me ! 
When registering a key, a sequence of random bytes is generated and then encrypted, also, a checksum of the upn is added to the resulting key for the registering user.
During authentication, the upn is verified and you receive this message "SECURTY ERROR: Invalid Key for User {0}, because the upn do not match...
**You must  regenerate a new key for this user (with the MMC for example)**

This behavior is a security feature.

Regards

**Comment by Steven2020-20** [comment]
Hello @redhook62 , thank you for the detailed explanation.  Should have tried adding a new key first by myself ... :) 
Makes total sense that a key is bound to exactly one UPN.

thank, and regards
Stefan

**Comment by BartHermans007** [comment]
Just for your information concerning other UPN names:

I'm working on the authentication of a new web site for our customers of the company.
A prerequisite was that the external user can log in with his personal email address instead of the UPN name of our AD domain name.

With ADFS it is possible to achieve that by configuring the use of AlternateLoginID. Using the command:
Set-AdfsClaimsProviderTrust -TargetIdentifier "AD AUTHORITY" -AlternateLoginID mail -LookupForests test.local
(test.local = AD domain name)
I tried it and it also works together with ADFS MFA. So you can choose whatever email address, you don't need to create a UPN suffix in AD. 

While using this configuration, the used email address is searched in AD. When found, that user is used for authentication.
When not found, the UPN's are checked. So you can mix using personal email addresses and domain UPN names.

Just to let you know.

Regards.

**Comment by redhook62** [comment]
Hi @BartHermans007 , @Steven2020-20 

First, the AlternateLoginID is used by Microsoft for AAD... The best practice is to use an UPN, with possibly adding some toplevelnames in ADDS.

Of course, it works with ADFS as Login ID like userPrincipalName or WindowsAccountName

Yes, it should work at this time with ADFSMFA, **but only if you have choosed the SQL Mode configuration for Storage**, 

This doesn't work with ADDS Mode configured, as indicated in the documentation ADFSMFA supports UPN and Windows Account Name (registry key before registering the product), in this configuration if upn is different from email, ADDS queries won't work.

Perhaps, a future évolution, but seems complex with multi forests and multi domains.

regards

**Comment by BartHermans007** [comment]
Hoi Redhook,

Thank you for your time.

I know that Microsoft recommends to use the UPN, but business asked me to investigate the possibility to log on with the users email address. Can you take a look at the attached file, proof of evidence? Just to be sure we are talking about the same functionality. Because I can do a log in with an email address and the ADFSMFA is configured with AD for storage. 

Regards.

[Test with email login name.docx](https://github.com/neos-sdi/adfsmfa/files/6290549/Test.with.email.login.name.docx)

**Comment by redhook62** [comment]
Yes, I will check for adfsmfa when ADDS is used.
However, email addresses cannot guarantee uniqueness, 
ADDS does not verify this. and that can be a big problem ...

But if it's OK for your project, so much the better.

regards

**Comment by redhook62** [comment]
Hi,

Yes it works for adfsmfa (SQL and ADDS).
adfsmfa receive the good value for the identity claim (aka: upn).
However, as i said, if you have multiple users with the same mail address, Login (forms) don't works, an error is generated by ADFS, this doesn't works also with Windows Authentication (Prompt).

regards

**Comment by BartHermans007** [comment]
Thank you for the validation! And I completely understand the risk of the implementation.
