### ISSUE TITLE
ADFS-MFA with enforced smart card logon

### ISSUE THREAD

**Issue by klpo-mt** [neos-sdi/adfsmfa#122]
Hi @redhook62, me again,

sorry to keep coming back, but I have another question which you can probably quickly answer.

We try to enforce smart cards for local computer login, but not after (i.e., to access a third party system in the network) nor at ADFS. By the looks of it that can be achieved by
- setting the smartcard force flag in Windows AD, which interestingly enough randomizes user passwords [....]
- then setting user's passwords back to their known ones

That does work so far on all AD-bound internal systems. Except for ADFS-MFA, configured with TOTP, which keeps rejecting the user password (prior to prompting for the one time code).

Is this a known and desired effect, and can we get ADFS-MFA to still accept that password?

Thanks a lot for your help,
Klaus

**Comment by redhook62** [comment]
Hi, @klpo-mt 

Would it be possible for you to provide links to the solution you are implementing ?

What I can tell you at first is that the MFA has nothing to do with primary authentication, it then triggers and relies on the user's UPN to start its job. it is a secondary authentication.

However, if you are using ADFS 2019 and have "Threat Detection" enabled, that actually can influence the login process.
See : 
Register-MFAThreatDetectionSystem
Unregister-MFAThreatDetectionSystem
Update-MFAThreatDetectionData

In order to check the operation
- deactivate the MFA on a relying party defined on your platform
- test in intranet (Windows authentication)
- test in extranet (Form Authentication)

If your smart card is correctly registered with Windows Hello, this should work.
As a rule, smart-cards are seen as authentication with client certificates, but very often use proprietary protocols.

For the MFA / WebAuthN part, it would be very interesting for us to see this work.
For information, this component is installed by a world leader in aeronautics, as a replacement or complement to the Gemalto SafeNet solution. 
We did not try to use SafeNet with adfsmfa, the solution is based on a proprietary COM component, and basically does authentication by client certificate with a dedicated backend. 
Although we being able to reverse obfuscated code, but the cost of implementation pushed us to leave the 2 solutions side by side ...

Feedback ?

Regards

Redhook

**Comment by klpo-mt** [comment]
Hi @redhook62,

meanwhile what I reported seems to be an issue (or by design) in ADFS itself and has nothing to do with the MFA provider. So can be closed. 

There's some discussion on the enforcement:
http://oamoim.blogspot.com/2020/01/smart-card-logon-enforcement.html
And in the comments the same behavior that we're struggling with is complained about.

Anyways, we run ADFS 2016 with ADFS-MFA using TOTP. Nothing on top. Smart card login on ADFS was not the intended goal. It was once, but that can stay with TOTP. We tried prior to proper WebAuthN support in ADFS-MFA with ADFS' built-in cert. auth., but ran into too many browser compatibility issues. The intent was to have smart card login on workstations, but TOTP MFA on ADFS.

By the looks of it, that can be achieved by enforcing SC logon on the workstations only, not on the user accounts. That's what we try next.

Thanks a lot though,
Klaus
