### ISSUE TITLE
support

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#125]
Hello

Do you provide a paid support service helping with implementation an MFA project for external companies or isn't possible?
I still have problem to configure biometric authentication on Windows and completely don't know how to resolve this.

Regards
Tryglav

**Comment by Tryglav** [comment]
I think i found solution. I cleared TPM on laptop i've tested on. After that configured windows hello signing methods were available for mfa.
But my question is open and i'm courious about this paid support service.

Regard
Tryglav

**Comment by redhook62** [comment]
Hi @Tryglav 

Very good.

the only things that are still missing on biometrics, because only recently published is support for Apple ...

Regarding support

We only do it for our customers (this solution is deployed in major French or international companies / organizations (Transport / Aeronotics / Industry / global organizations) because we have projects with them. We are therefore in able to develop specific versions under our projects or maintenance contracts if there are any with them.
The project also received funding for R&D in France.
We also have the option to participate in the Github Sponsors Program, but have not activated it ...

Regarding Github 
It remains above all a code sharing platform for developers, it's open-source, although we provide binaries, it is not a product (see the MIT license conditions). 
As you may have noticed, we are following this project with the greatest attention and will respond to requests when they are legitimate (concerning the project bugs, evolutions, configuration, etc.) but not internal problems of each person having retrieved the build. we can't do that, we don't have a clear vision of every stargazer environment.

Now you can always contact Neos-sdi, but I know that in the past this type of initiative was not successful.

Regards

redhook
