### ISSUE TITLE
user can skip MFA enrolment even when selected it as mandatory  

### ISSUE THREAD

**Issue by AmeerErg** [neos-sdi/adfsmfa#136]
Hello My friend,
Really appreciate the amazing work you have done.

We faced an issue, we selected mandatory MFA can not be disabled as below 

![image](https://user-images.githubusercontent.com/37581750/103540025-1ba2e800-4eaa-11eb-95ed-e3ebc0f9cf2e.png)

However in ADFS we get the screen below where you can skip the MFA registration by selecting sign in button as below and hence you will have users without MFA 

![image](https://user-images.githubusercontent.com/37581750/103539966-062dbe00-4eaa-11eb-8123-20e7d32e768a.png)

-------------------------------

Is this a bug ? can you force the user to register/enroll for MFA in order to access the system ?

Thank you again.

**Comment by redhook62** [comment]
hi **@AmeerErg** 

No, it's not a bug. it's the "default" configuration.
The user is invited to register for MFA, but he can skip if he want... (no time to lost...). it will be notified between the fisrst day and las day properties each month.

You must select "Mixed Template" or take it as a model to achieve this.

What is your MFA version ? because we cannot reproduce your problem ?

Regards

- To let users to "bypass" MFA

![image](https://user-images.githubusercontent.com/26826945/103544858-01184100-4ea1-11eb-8e39-b646488abaa4.png)

- To force users to register

![image](https://user-images.githubusercontent.com/26826945/103544678-c1515980-4ea0-11eb-91c0-50bb1125995b.png)

Or 

![image](https://user-images.githubusercontent.com/26826945/103544567-96ff9c00-4ea0-11eb-86e1-c9b6d8b270b4.png)

**Comment by AmeerErg** [comment]
Hello i am still facing the same issue, I am using the latest version 3.0.2101.0 and my configuration as below 

![image](https://user-images.githubusercontent.com/37581750/103548860-75f67580-4eb7-11eb-9f06-28786f2c9fbb.png)


I noticed whenever i use a custom template it does not work.

Thanks again.

**Comment by redhook62** [comment]
Hi **@AmeerErg** 

We can't reproduce your problem.
It seems that your modifications are not loaded properly.

Have you more than one ADFS server ?
Have you configured WsMan and Firewall rules ?

Regards

**Comment by AmeerErg** [comment]
Hello again it is only one ADFS no modification for WsMan or firewalls since installation.

I would like to point out that when i changed it to mixed template everything works with the additional management options i am trying to avoid

One last point is, i upgraded the MFA from pervious version to the last one so this might be causing the issue of custom template not working properly while mixed template works fine.

**Comment by redhook62** [comment]
I have tested with exactly the same paremeters you have provided, and no problem for me (2019/2016/212r2).

When you launch a new console, does the parameters ar filled as well ?
Have you tried to restart the adfs service ? **Restart-Service adfssrv" 
Have you tried to restart the MFA service ? **Restart-Service mfanotifhub" 

If you have only one server, firewall rules are not needed.
But, try to enable correctly WsWan see : https://github.com/neos-sdi/adfsmfa/wiki/07-Security#wsman-security-properties-description

**Comment by redhook62** [comment]
Some news ?

**Comment by sathyajackson** [comment]
@redhook62 ,

Select Mixed in general settings then restarts the services. This will fix your problem.... if still the problem presist, restart all the Federation services and check.

I had a similar issue, and mixed fixed my issue.

**Comment by sathyajackson** [comment]
Sorry the above post is for @AmeerErg
