### ISSUE TITLE
Very slow authentication/administration

### ISSUE THREAD

**Issue by jcbuache** [neos-sdi/adfsmfa#139]
Hello,

I successfully installed the latest version (3.0.2101.3 - fresh install). Creating a user in the MMC is very slow (when clicking on the key tab, about 40 seconds to get the button "New Key", then again 40 seconds to display the qr-code, and 30 seconds to close the window when clicking "OK"). 

When using it for connecting, when trying to connect with TOTP, verifying the password takes several dizains of seconds before displaying the "code" field, and then again several dizains of seconds before sending to the Service.
Enrollment is the same.
Same problem appears when using the e-mail as second factor.

![image](https://user-images.githubusercontent.com/77742917/105206637-e43d6800-5b46-11eb-98f9-e9f9119f01e6.png)

There is no entry in the Application Event Viewer.

We have 2 ADFS 2016 servers, 14 Active Directory servers. The domain counts more than 70000 users.

I imagine trying to store the configuration in SQL Server, but not sure it will help. The documentation mentions version Standard or Enterprise. Could it work with the free Express version?

Thanks in advance,
jcbuache

**Comment by redhook62** [comment]
Hi **@jcbuache**

First, you have 14 ADDS forests and 70,000 accounts.
When you log in to one of 14 forests (before the MFA) does it take time?

For the different remote forests does the network works fine ? (poor network performance in your trust relationships) ???

Do you use a "superuser" account, which can read and write in all your ADDS ???

Have you activated anti replay? (be careful! the firewall rules must be open between your ADFS servers, as indicated in the documentation). otherwise there is a WCF timeout between your two ADFS servers.

Obviously in your configuration it is preferable to store the MFA information in an SQL database accessible to your AD FS servers. 

For SQL Server the Standard version is more than enough, unless you want to use the "Always Encrypted Colums", in which case the Enterprise version should be preferred. 
Only one database will be created, 
We have had customers with as many users as you have for several years.

So Using SQL Server (or other) this is the preferred route. The Express version is not supported.

When we talk about performance optimization for the next version, this directly concerns only the console and PowerShell Cmdlets, 
The site does not require optimization, it is up to you to ensure that the "Storages Backends" are accessibles and efficients.

Regards

@redhook62

**Comment by jcbuache** [comment]
Hi @redhook62,

Many thanks for your answer. I apologize for confusion, there is only one forest and one domain, but replicated in 14 servers around the world. There is no apparent network issue and I confirm that if the MFA extension is disabled, the login takes less than one second.

I verified the firewall configuration and both ADFS can communicate through port 5987.
The account used is operator admin, this should be enough.

I will try to setup the SQL Server database now and keep you posted.

Is there a way to enable some debug logs to see if something weird happens?

Many thanks,
jcbuache

**Comment by jcbuache** [comment]
Hi again @redhook62,

This is to confirm that using SQL Server mode works like a charm!
I take this opportunity to thank you for this great tool!

If possible I'm still interrested in having some debug logs to try to understand why it is so slow with ADDS mode. My feeling is that even with a lot of users it should be able to work.

Many thanks for you help!
jcbuache.

**Comment by redhook62** [comment]
Hi **@jcbuache** 

Really, I don't know why it was so slow on your platform, there's only one domain, and user information is lookedup directly by their UPN (unique key), only the console pulls up a paginated list as well as some PowerShell commands (Search List of users or imports from ADDS).

In the past, we have already had Forests with more than 70,000 users. Maybe the structure of your OU ??
With SQL we have carried out extensive tests with une database and more than 450,000 users without slowdowns.

Yes, there are logs but they are for errors.
We are thinking to include performance counters in a future version.

regards

redhook

**Comment by redhook62** [comment]
Yes, bug confirmed
Investigating !

Regards

**Comment by redhook62** [comment]
N
