### ISSUE TITLE
MMC Console error

### ISSUE THREAD

**Issue by AJHoek** [neos-sdi/adfsmfa#14]
Hi,

We are testing using the latest 2.0.2.967 version.
Server is a Windows 2012R2 edition, the plugin itself is working when configured through Powershell.

We have an issue with the MMC console which gives an error "MMC could not create the snap-in".
Are we missing any prerequisites?

Regards,
AJ

**Comment by redhook62** [comment]
Hi, 

No ideas !

Can you publish some eventlog errors, 

The MMC Snapin is accessing metadata from ADFS's Database via PS (the same code as the PoweShell cmdlets).
You must use an account with suffisant rights (eg Local admin on ADFS212R2).

Let us know

Regards

**Comment by redhook62** [comment]
Hi,

We found the problem !
NotificationHub Service and MMC Snapin doesn't register properly if UAC is enbled for local Administrator.
We are going to check the Wix installer. 
but many problems since the last update of Microsoft (be very carefull on Windows 2016 and KB KB4077525)

As WorkAround, launch gpedit.msc.
Computer Configuration ->
Windows Parameters ->
Security Parameters -> 
Local policy -> 
Security options -> 
**User Account Control: Administrator Approval Mode for the Integrated Administrator Account**

Set it to **Disabled**.

**Only** Uninstall and reinstall the adfsmfa.msi.
 
Regards
redhook

**Comment by redhook62** [comment]
New version 2.0.2.968.
You can enable now UAC for administrator

Regards
