### ISSUE TITLE
Remotely execute powershell commands (Invoke-Command)

### ISSUE THREAD

**Issue by JustITPL** [neos-sdi/adfsmfa#143]
Hello,

I have problem with remotely execute powershell commands. ADFS commands work properly (on the same account).

Sample: Invoke-Command -ComputerName xxx -ScriptBlock {Get-MFAUsers -Identity yyy}

![image](https://user-images.githubusercontent.com/78961810/107766431-bdccb000-6d33-11eb-9afa-469c88c29fdd.png)

**Comment by redhook62** [comment]
Hi, **@JustITPL** 

As you can see in "Neos.IdentityServer.MultiFactor.Admin.Cmdlets.cs" remoting is not allowed !
All  the *-MFAUsers cmdlets **can be executed on each ADFS server** (WID or not).
So, we have to evaluate the impact ot changing this behavior...

regards

redhook

**Comment by redhook62** [comment]
Hi, **@JustITPL** 

We think that it"s possible, and we are planning to implement this.
At this time, we need to impersonate the user for accessing ADDS or SQL Server (AUTORITE NT\ANONYMOUS LOGON).
We plan to use the super account to achieve this.
Does this is Ok for you ? And please wait some days for a release.

regards

**Comment by JustITPL** [comment]
Hi @redhook62 

Ok, but do You see I'm execute cmdlet on ADFS server using Invoke-Command from My computer with adfs admin cred (sample: Invoke-Command -ComputerName ADFS-Server ...)?

Solution for now it's ok but...
Is possible to implement manage MFA based on security group? 

Medium company have operators of Service Desk and company must delegate they permissions to manage MFA users. Adding this peoples to ADFS admins it's not good thinks.

**Comment by redhook62** [comment]
Hi, **@JustITPL** 

With version 3.1, all the security is governed by the ADFS security configuration.
**This is working as well with non remoting PowerShell.**

You can put any ADDS group in the local Administrators group of each server, or better put any ADDS group in the ADFS Delegated Administration Group.

All ACLs in adfsmfa are done according this (Folders, Certificates, Mailslots, ...)

We have just to solve the problem when using PowerShell Remoting.

Witch kind of configuration are you using for MFA ? ADDS/SQL Server ?
Witch kind ot configuration are you using for ADFS ? WID/SQL Server ?
How many ADFS servers do you have ? What is your ADFS Version ?

regards

**Comment by JustITPL** [comment]
Hi @redhook62

Ok, but that's not good practice of "Just Enough Administration". 
Service Desk should have permission only to manage users. 
I wrote powershell script with GUI to manage users in ADFS MFA, but i can't give them this, because We work with JEA and I can't give them ADFS Admins.

Witch kind of configuration are you using for MFA ?  ADDS
Witch kind ot configuration are you using for ADFS ? WID
How many ADFS servers do you have ? Two
What is your ADFS Version ? 4 (2019)
ADFS MFA: 3.1

**Comment by redhook62** [comment]
Hi, **@JustITPL** 

I am beginning to understand your request.
If I summarize, you want your AD FS operators to be able to manage only users without being able to access ADFS servers so using PowerShell Remotes commands.

We will therefore move forward in stages, because you can imagine the product is becoming complex, and this forces us to do a lot of tests in addition to the development.
- The remote Powershell first within a few days.

Then I suggest you put a Pull Request, to tell us your vision. 
What are the groups of users distinct from you want (MFA Users management Admins? MFA Full Management Admins?), And tell us which features will be accessible (PowerShell Cmdlets, MMC Snapin).
We have some ideas, but it will be  cool to have your inputs

regards

**Comment by zjorz** [comment]
> ADFS Delegated Administration Group

With or without ADFS delegated Admin, the following is not working. Using v3.1.

PS C:\Users\ADM.ROOT> **Register-MFASystem**
Register-MFASystem : PS0033: This Cmdlet must be executed with ADFS Administration rights granted for the current user !
At line:1 char:1
+ Register-MFASystem
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Register-MFASystem], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,MFA.RegisterMFASystem

PS C:\Users\ADM.ROOT>

I get the exact same error "This Cmdlet must be executed with ADFS Administration rights granted for the current user" for may cmdlets, while is allowed to do anything in AD, windows and ADFS. So something is wrong as not having the correct perms does not apply here

any hints?

regards,
jorge

**Comment by redhook62** [comment]
Hi **@zjorz**, **@JustITPL**

Yes, we are working on it, there will be a version soon.

However, for security reasons, we will only allow user management cmdlets (* -MFAUsers).
It does not seem wise to us to initialize the component (Register-MFASystem or other) in Remote PowerShell. 

It will be "by design"  !

regards

redhook

**Comment by zjorz** [comment]
Hi,

This is NOT remote. This is LOCALLY on the primary adfs server. I installed the software and I want to initialize it and that is not working due to some perms error which I do not understand nor do I know where to even start looking

Can you help?

Regards,
Jorge

**Comment by abe57330** [comment]
Hi everyone, 
I am also getting the same issue than zjorz. 

Error message "Register-MFASystem : PS0033: This Cmdlet must be executed with ADFS Administration rights granted for the current user !"
This is run from local adfs powershell, connected as domain administrator or adfs admin delegated group member account.
I tried on both a win2019 and a win2016 -> same result.

Actually, any MFA* cmdlet will throw the same error, despite I am able to run ADFS cmdlets.
Since this is lab, I only have one adfs server in the farm.

I'll try tomorrow previous versions and will let you know the results.

Best regards,

Anthony

**Comment by zjorz** [comment]
@redhook62 
Is there a workaround to be able to install?

**Comment by redhook62** [comment]
Hi All

Yes, bug confirmed on version 3.1.2101.0 (Register-MFASystem)
Wait for the next one, and go on the one at the end of January

regards

**Comment by abe57330** [comment]
Hi,

Not sure it is helpful but I confirm I can run cmdlets after switching back to v3.0.2101.3

Best regards.

**Comment by redhook62** [comment]
Hi All

We confirm 3  things.
- Remoting PowerShell was not supported/implemented in version 3.1.2102.0, it should be available in version 3.1.2102.1 next week
- Acces denied on any Powershell System commands (except *.MFAUsers)
- You cannot register a new configuration (Register-MFASystem and others), it seems to work with existing configuration (for us, it was working with an ADFS SQL configuration)

So, we removed the buggy version, an are working for the next (next week), with intensive tests for all possible configurations
- 2012 r2 alone and Farm (WID and SQL), New Config and Existing config -> 8 configurations
- 2016 alone and Farm (WID and SQL), New Config and Existing config -> 8 configurations
- 2019 alone and Farm (WID and SQL), New Config and Existing config -> 8 configurations

best regards

**Comment by redhook62** [comment]
Hi All

New Release 3.1.2102.1

regards

**Comment by zjorz** [comment]
Thanks. I will try this out
Regards 
Jorge

**Comment by zjorz** [comment]
installing and registering now does work, but there are other issues
