### ISSUE TITLE
Warning message when installing RSA certificate

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#15]
Hi,
I get a Warning when I install a certificate for RSA encryption. 

Both the command:
`Install-MFACertificate -RSACertificateDuration 5 -RestartFarm -Verbose`

and the command :
`Register-MFASystem –Activate –RestartFarm -KeysFormat RSA -RSACertificateDuration 5 –Verbose`

gives the warning:

> WARNING: 4:23:05 AM Error adding certificate "0A2B697C59C4C42EF595D34F91DB0FA666455E1F" to ADFS Decrypting Certificates list, your must do it manually !

Everything seems to work though. 
What manual process is the message referring to? 
Or could this message be ignored?

Kind Regards,
Andreas

**Comment by redhook62** [comment]
Hi,

No, you can ignore this warning. 

It's normal, because you are in AutoCertificateRollover mode.
`Get-AdfsProperties -> AutoCertificateRollover = true`.

A new certificate cannot be added in adfs store in this case 
see : [https://docs.microsoft.com/fr-fr/azure/active-directory/connect/active-directory-aadconnect-o365-certs]

So the RSA cert cannot be replicated between ADFS Servers (when in WID mode)

Regards

**Comment by anorstrom** [comment]
Ok, got it.
Thank you for replying!
