### ISSUE TITLE
Registration wizards behavior / settings

### ISSUE THREAD

**Issue by abe57330** [neos-sdi/adfsmfa#159]
Hi team,

Version used: 3.0.2101.3

During the first connection, a user is asked to register an authenticator app, AND to provide an email address:

![image](https://user-images.githubusercontent.com/79278323/110652574-ca221c80-81bc-11eb-91b8-bd6c7c1bb515.png)

While the Email MFA provider Enrollement Wizard is disabled:

![image](https://user-images.githubusercontent.com/79278323/110652775-f76eca80-81bc-11eb-99ab-c40c33a84d3e.png)

And the last one, because both TOTP and Email MFA are set to Required, I guess the "Sign-In button" should not be displayed at this step.

![image](https://user-images.githubusercontent.com/79278323/110653155-4d437280-81bd-11eb-9b27-f643ba38d04e.png)

Here are my global parameters for information:

![image](https://user-images.githubusercontent.com/79278323/110653302-69dfaa80-81bd-11eb-8f50-34c4bb335d23.png)

Best regards.

**Comment by redhook62** [comment]
Hi, @abe57330 

During the registration phase, the user is asked to provide the requested elements for all the Active providers.

Wizards will no longer be offered if you have deactivated the option to use Wizards.

We will check for the "Sign-In" button, because in your configuration it is not possible to bypass the recording options in general, but only on providers marked as optional.

regards

**Comment by abe57330** [comment]
Just to clarify, we would like to pre-provision user's email address, and let him register his TOTP by himself.

The only way I found to to this is to login another way at first connection, with email sent OTP then, and after use the "Access my options after authentication" to go to the "Enroll my authentication application" link. But this adds a few steps for the final user.

I guess in my scenario the registration wizard "Configuration Options" is not displayed because I already enrolled an email address from the MMC console. And when doing this, it is mandatory to also generate a secret key.

I clearly understand your logic, but that would make sense, in my opinion, to check at this step which providers are Enrollment Wizard allowed, and display only the allowed ones.

Hope it helps.

BR

**Comment by redhook62** [comment]
Hi @abe57330 

In the mode you have configured, you have chosen to let the users register themselves (Registration made by the user). in this case the user must provide the information for all Active MFA providers (mandatory or not, with wizards support or not), otherwise we would have no way of obtaining the necessary information.

What you can achieve, we have already implemented it with some customers, the template is more restrictive (Administrative or custom with the right options)

![image](https://user-images.githubusercontent.com/26826945/110663092-6ef52780-81c6-11eb-967c-9a4b4e78a988.png)

Then you can provision your users with one of the methods described in the documentation (csv, xml, ADDS)
here : https://github.com/neos-sdi/adfsmfa/wiki/09-Users%20Management#import-management-operations.

Let us know if this help you

regards

**Comment by abe57330** [comment]
Hello,

Tested your suggested config with v3.0.2101.3, and it is successfull, thanks a lot for your help.

Best regards.
