### ISSUE TITLE
Slow response when logging in using biometrics

### ISSUE THREAD

**Issue by MrPanNikt** [neos-sdi/adfsmfa#169]
Hi,

After installing the latest version (3.1.2104.1) of the application, there was a problem with the login time with the Bioimetry device. The time from logging on to ADFS to being asked for 2FA is from 21s to 50s. It makes no difference to the device vendor and it doesn't matter whether the user is on the local network or on the Internet. When logging in with 2FA as e-mail or TOTP, it takes about 4s. In a test environment with a single ADFS server, there is no such problem. There is the same division of domains in the environment, i.e. root and two children domains.

Using Biometric time respons

![Bio](https://user-images.githubusercontent.com/63781655/117004646-978d2f80-ace6-11eb-87bc-d79d0b538422.PNG)

Using TOTP time respons

![Use_TOTP1](https://user-images.githubusercontent.com/63781655/117004931-f18df500-ace6-11eb-9fbc-a7b5d5c29e5a.png)

Environmental Specification
2x ADFS - windows server 2019 std
2 subdomains in the one root domain
approximately 10,000 users, 200 of which have MFA enabled and configured
Windows Server 2008 R2 tree and forest level

**Comment by redhook62** [comment]
Hi @MrPanNikt 

The version you installed does not change anything with respect to LDAP queries on domain controllers.

If the login / password times are correct you can disable the support for the detection of passwords policies if this is activated (ADDS Password Policy settings, ADDS Fine-Grained Passwords Policy settings).
[Passwords Policies settings](https://github.com/neos-sdi/adfsmfa/wiki/07-Security#managing-mfa-security-with-mmc)

We have done tests with several drills and subdomains (several hundred users) and have not noticed any slowdowns, when Password policies are activated it is indeed a little longer (~ 1s)

Otherwise, there is necessarily a problem at the network level for LDAP requests

regards

**Comment by redhook62** [comment]
Hi, @MrPanNikt 

If the problem only arises when you have several ADFS servers, 
there is a communication problem between your servers. 
the durations indicated correspond to the Timeout of calls between servers. you must find traces of these errors on the machines eventlog

You can check the rules of the firewalls on your servers
Use the Set-MFAFirewallRules cmdlet to correctly position rules between servers.

regards

**Comment by MrPanNikt** [comment]
Hi, You can close the task. The problem was actually in the configuration, it was precisely related to the response time of the root domain controller that was in a different location. Putting a second controller in the same location as the ADFS servers solved the problem. Thanks for your help and anliza.

**Comment by redhook62** [comment]
Great !

regards
