### ISSUE TITLE
Need administrator rights - help 

### ISSUE THREAD

**Issue by Martin-Gardner** [neos-sdi/adfsmfa#170]
I am trying to install this for use with hello for business in a home lab - I have followed the following guide for set up:

https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-deployment-cert-trust

I have installed on server server (SAC) (sever core) and I have added the application compatibility options for MMC.exe and copied over the missing msc data and registry - this seems to work file - I can open the adfs msc and configure options. I am unable to open the MMC for this application or even use the power shell script - it states I need to be in the admin group - i am logged in using domain and enterprise admin account which has been added to the adfs server local admin group specifically and i have tried the local administrator account on that server - I have ticked the box which should allow local admins to access - but each time it throws up - you need to be in the admins group - can you provide any insight into this - it would be on much help. I can provide more information if requested.

Kind regards and thanks you your time reading.

Martin

**Comment by redhook62** [comment]
Hi @Martin-Gardner 

I think you need to restart the MFA service, 
on restart the systems.db file will be recreated with the correct ACLs stored inside.

You will need to do this each time you change the rights items in the AD FS console. 
you must also close and reopen your session on the server, because the user's Windows token is hidden by the system.
alternatively,  You can also delete the system;.db file in ProgramFiles \ MFA \ Config

regards

**Comment by redhook62** [comment]
Some news ?

**Comment by Martin-Gardner** [comment]
Sorry. I will reply properly later

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
