### ISSUE TITLE
Safari and TouchID

### ISSUE THREAD

**Issue by PsySuck** [neos-sdi/adfsmfa#190]
Hi.
I am faced with the problem that I cannot use touchID in safari. This works in all browsers except safari.
When I try to use touchID, I see this error.
_This request has been cancelled by the user._
Here is my config for test.
`AuthenticatorAttachment         : Empty`
`AttestationConveyancePreference : None`
`UserVerificationRequirement     : Discouraged`
`Extensions                      : False`
`UserVerificationIndex           : False`
`Location                        : False`
`UserVerificationMethod          : False`
`RequireResidentKey              : False`
`HmacSecret                      :`
`CredProtect                     :`
`EnforceCredProtect              :`

**Comment by redhook62** [comment]
Hi, @PsySuck 

It is normal that this works with browsers which fully support the protocol.
Safari, is certainly more restrictive because your attestation type is set to "None". 
Although Apple has been interested in WebAuthN quite recently, not to mention their willingness to impose their views on the IETF.
I think you should at least change the attestation type and ask for user presence verification. 
On None attestation, there is not even assertion checking ...
Please refer to the documentation on the Biometric provider and be inspired by the examples given.
You will need to re-register your device in this case.

In September, we will be doing an update of the WebAuthN part, which should include changes related to Apple.
Do not hesitate to follow this project, in order to be notified of new versions.

regards

**Comment by PsySuck** [comment]
Thank you.
I tried different combination of options, but then i try to enroll via safari i got: 
`Your account is not validated !`
`You can try the operation again by selecting "Previous".`
`This request has been cancelled by the user.`

Have you tested TouchID in safari?
Seems to be a limitation of apple.

https://github.com/w3c/webauthn/issues/1453

**Comment by redhook62** [comment]
@PsySuck 

As stated, Apple has changed a lot of things. 

We tested with Safari and FaceID on an iPhone 12, and obviously it does not work (attestation format changed ...), 
Safari works correctly with Yubico security keys and NFC.

We do not rely on the library you indicate, for ADFS, we are in .Net (passwordless-lib/fido2-net-lib).
You can test with the demo site https://fido2-net-lib.passwordless.dev , the last implementation dating from the end of May 2021.

https://github.com/passwordless-lib/fido2-net-lib/issues/209
https://github.com/passwordless-lib/fido2-net-lib/pull/205
https://github.com/passwordless-lib/fido2-net-lib/issues/184 (done)
https://github.com/passwordless-lib/fido2-net-lib/pull/175

We will integrate these changes in September, until everything is perfectly stable.

regards

**Comment by PsySuck** [comment]
Thank you!
I will wait update.
Can i ask another question in the same trend? Is it possible to have dedicated self-service portal for management of user settings?

**Comment by redhook62** [comment]
Hi, @PsySuck 

You must know that you have a console and powershell commands for administration.
Users can manage their own information.

It is not possible to put a web server on ADFS servers, the ports are occupied by ADFS (http.sys)
So, we stayed in Microsoft's logic, making sure to properly manage all aspects of security.

Creating a portal is not impossible, it would be necessary to read and write the data from the repositories (ADDS, SQL, Custom) and to be able to manage the encryption part.

I think that we will not do a Portal (in what technology?), But maybe an extension of the MFA web service for CRUD operations on users, obviously with high security.

regards

**Comment by PsySuck** [comment]
Thank you for you answer.
