### ISSUE TITLE
After entering the password, the message "SECURTY ERROR: Invalid Key for User" is displayed

### ISSUE THREAD

**Issue by motocmo** [neos-sdi/adfsmfa#196]
SECURTY ERROR : Invalid Key for User
![image](https://user-images.githubusercontent.com/32262463/137472168-2da24a58-c62d-41ce-bbe0-a3db2f3e510f.png)

**Comment by redhook62** [comment]
Hi, @mojintang 

This error is very specific. 

It only occurs when the UserID (UserPrincipalName or WindowsAccountName) does not match the values stored in the user's key.

If your identification claim is userPrincipalName (default), either this value is null in your ADDS, 
or you have changed your UPN, 
or someone else's key has been copied to your profile.

You can look at this issue : https://github.com/neos-sdi/adfsmfa/issues/117

You must therefore verify your identity claim, and once the problem has been identified and corrected.
Please regenerate a new key for this user

Thanks, there is a typo error in the label

regards

**Comment by redhook62** [comment]
Support for TOTP codes have existed since the first version of the product (5 years ago), and are of course compatible with all phones (iPhone included). it is an authentication application that calculates the code according to the IETF rfc6238, based on a hash and the current time.
Did you scan the QRCode correctly with your iPhone? Which authenticator app do you use? make sure you refer to the TOTP codes (rfc6238). To share the TOTP code on several phones you must scan the same QRCode on both phones or use the Authy authentication application which allows synchronization of TOTP codes on several devices.

regards

**Comment by mojintang** [comment]
Restarting the server is normal now. In addition, there is another problem. After entering the password, click sign in in in the picture to skip the secondary verification and log in directly (as long as there is no registration, so is the subsequent login). Only when you click registration can you log in through secondary authentication (secondary authentication is mandatory for subsequent login). Is there any way to turn off the sign in button? I need to force users to turn on secondary authentication.
![signin](https://user-images.githubusercontent.com/32262463/138210276-ab6840f9-e2ba-4e0d-aa53-f2720d84570c.png)

**Comment by mojintang** [comment]
I found it. It's related to custom template settings. thanks.

**Comment by mojintang** [comment]
I have another problem. Select the second item in the user-defined template to allow users to customize registration. There will be a sign in button. Clicking login will require secondary verification. Only selecting the registration button will enable secondary verification. Is there a way to turn off sign in? Selecting the first option requires biometric verification, which cannot be used.
![signin](https://user-images.githubusercontent.com/32262463/138216089-5e4b323e-6d3b-4f0e-99f6-0fe146ddb747.png)

![image](https://user-images.githubusercontent.com/32262463/138215801-67c89fb7-0f59-4250-95b0-fdb545cafbe6.png)
