### ISSUE TITLE
Invalid identification, please restart your session.

### ISSUE THREAD

**Issue by xeonkeeper** [neos-sdi/adfsmfa#30]
I cant autentification by mail (other methods i' cant tested). I have two 2016 ADFS and two 2016 Application proxy with HAProxy.
ADFS servers in failover mode, but now only one in use (by DNS record).
What I've done:
Setup adfsmfa.2.2.0.25.msi on both ADFS servers. 
Run:
Register-MFASystem –Activate –RestartFarm –KeyFormat CUSTOM –RSACertificatDuration 2 –Verbose
New-MFADatabase -ServerName acod-msdb-cl -DatabaseName MFADatabase -UserName company\svc_adfs
New-MFASecretKeysDatabase -ServerName acod-msdb-cl -DatabaseName MFAKeysDatabase -UserName company\svc_adfs
All databases created successfully

Account svc_adfs member of domain admins group and in local admin group on ADFS server for testing.
Setup global and SMTP properties.
Change Access Control Policy to MFA for my application.
Then, i'm create user in MMC MFA console with UPN user@company.com and email user@company.com.

When i go to https://myapplication.company.com i'm redirection to page with "Access code received by email :" and paste my code from mail. But when i'm push "Sign In" i see message "Invalid identification, please restart your session."
What did I miss in the setup and what am I doing wrong?

**Comment by redhook62** [comment]
Hello xeonkepper.

Yes, it seems your configuration is right.
there's an issue, related to this feature https://github.com/neos-sdi/adfsmfa/issues/29.
the problem occurs if the adfs externalLockout is not enabled.
As quick work around you can enable external lockout on your ADFS Farm.

**Enabling External Lockout :**
` `Set-AdfsProperties -EnableExtranetLockout `$true -ExtranetLockoutThreshold 3 -ExtranetObservationWindow (new-timespan -Minutes 30) `

**Disabling External Lockout** : 
` Set-AdfsProperties -EnableExtranetLockout $False `

https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection

**Comment by xeonkeeper** [comment]
Thanks! That helped me.
I've got one more question. Can i use SQL mode, and auto-create users with first logon with his "mail", "phone", "UPN" properties from AD?

**Comment by redhook62** [comment]
Yes, your users can register themselves, provided they have selected as a template in the MMC "Default Template".

For import from Active Directory, new things are planned in future releases. Can you confirm that with less than 6000 users the import works.
Using the database to store users (SQL Mode), some tests with 450,000 users were made without any worries.

Regards

**Comment by xeonkeeper** [comment]
Now i'm tested AD import. After click ok button to import processor loaded in 95% and users creating in database, but not displayed in MMC. Another strange thing that in database only 1000 entries. Seems like a limitation LDAP query?

**Comment by redhook62** [comment]
Yes, By default LDAP queries results are limited to 1000.
It's possible to bypass this behavior, but How Many ? we will put a new parameter for that in future beta.

Yes, bug with ommited parameter in cmdlet Add-MFAUsers.

If your user exists in the database, your must use `Set-MFAUsers` cmdlet, not `Add-MFAUsers`.
If You don't see any users after import in MMC, it's because the view is filtered, disabled users are invisible until you clear the filter. You can also use `Get-MFAUsers` with adequate parameters.
Until the account is enabled, the user cannot use MFA and perhaps access is denied depending of the policy settings.

Remember, that the actual version is a beta version, so, you must limit the use for testing and not for production.

Wait a little bit for new version

Regards

**Comment by redhook62** [comment]
New beta 2.2.0.34
