### ISSUE TITLE
Include Pull Request #36

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#37]
Hi,
I think the closed Pull Request #36 made by @Ikke should be merged and included in the release.
Tested the changes, and when running the [Microsoft Centered UI](https://github.com/Microsoft/adfsWebCustomization/tree/master/centeredUi) experience, these changes fix issues in the TOTP enrollment pages.

Besides that 2.2.0.39 worked nicely!

Kind Regards,
Andreas

**Comment by redhook62** [comment]
Thanks

**Comment by redhook62** [comment]
Missed !

**Comment by redhook62** [comment]
New Version 40

**Comment by anorstrom** [comment]
Tested the new version 40 and white space is now added to the first page in the TOTP enrollment, so that looks nicer when running MS Centered UI. 
However, the rest of the pages in the TOTP enrollment does not have that white space. Could these be fixed too in the same way?

**Comment by redhook62** [comment]
@anorstrom

Yes, of course it's possible to modify the pages of the wizard.
You will soon have a new build. this night.

However, it's important for us that the default theme remains also perfectly functional.
And, the theme of Microsoft (in alpha) begins to impact the standard.
You will be able to post issues to "MS Centered UI", because from this point of view it's their problem (CSS).

I think, my very, very old friends from Microsoft will be able to answer you. Yes, you do it before...
Indicate to them that the "mercato" is finished, it would be desirable to target a version 1.0 for production by next spring :)

The current version, will come out of the beta phase. Next week the documentation will be updated.
We will quickly follow on, the biometric authentication WebAuthN which is very promising (https://fido2.azurewebsites.net)

Best Regards

**Comment by anorstrom** [comment]
> @anorstrom
> 
> Yes, of course it's possible to modify the pages of the wizard.
> You will soon have a new build. this night.
> 
> However, it's important for us that the default theme remains also perfectly functional.
> And, the theme of Microsoft (in alpha) begins to impact the standard.
> You will be able to post issues to "MS Centered UI", because from this point of view it's their problem (CSS).
> 
> I think, my very, very old friends from Microsoft will be able to answer you. Yes, you do it before...
> Indicate to them that the "mercato" is finished, it would be desirable to target a version 1.0 for production by next spring :)
> 
> The current version, will come out of the beta phase. Next week the documentation will be updated.
> We will quickly follow on, the biometric authentication WebAuthN which is very promising (https://fido2.azurewebsites.net)
> 
> Best Regards

Yes understand, important to support default theme of course. I tried to open a few tickets at the MS repo, but they do not respond very fast ;). Thank you for fixing this! Tested version 41, and it looks nice now in the Centered UI.

Would be really nice if you could get FIDO2 support into this solution! Looking forward to test that :)

Thank you,
Andreas
