### ISSUE TITLE
Language select

### ISSUE THREAD

**Issue by xeonkeeper** [neos-sdi/adfsmfa#38]
Can you improve the feature to change default language and titles without project build in VS? It's may be separate XML files and etc? I want to translate to cyrilic. 
Other things work great for now.

**Comment by xeonkeeper** [comment]
Ok, i to be translating .resx to rus soon) But, i'm mean other. A lot of people using english backend, not need to be translating it. But front end, for usual employees, need to be translating to native language simply, without build project in VS. The same way, administartors can wont to change some titles. 
Logically, it is good to make these settings in external files of the type C: \Program Files\MFA\ languages \rus\languagerus.xml

**Comment by redhook62** [comment]
Ok, I understand your position.
It's also a question of security, no external code !

Also a lot of people taking this component do it with good reason or because they do not trust Microsoft's MFA (look at the Azure Provider code) or have to pay for it.

We also want this component to become "industrial as possible" that can be deployed in an ADFS server farm without worries.

You can only translate the UI Web parts and omit the console and the powershell if you wish.
By integrating your language, it may be that others will be very happy to benefit from your participation.

 moreover the source code is available and modifiable according to your wishes, we made the effort to package all, that is not really common on GitHub where we mostly share code.

If you post the resx, we will integrate them immediately.

Thanks
Best regards
