### ISSUE TITLE
ActiveDirectory mode, deactivated user

### ISSUE THREAD

**Issue by Snorre33** [neos-sdi/adfsmfa#50]
Hello

I am not really sure if it is a bug or planned in this way.
I am testing version 2.2.0.1002.

After deactivation of a user the user disappears completely in the gui and also in PowerShell.
Reactivation is only possible with changing the field msDS-cloudExtensionAttribute18 back to true with the attribute editor.

Thank you.

**Comment by redhook62** [comment]
No, it's not a bug

Get-MFAUsers -IncludeDisabled

![image](https://user-images.githubusercontent.com/26826945/50973932-658aaa80-14ea-11e9-90ec-ee2dd4edea7f.png)

![image](https://user-images.githubusercontent.com/26826945/50974010-8d7a0e00-14ea-11e9-9ebe-5f02642a4b34.png)

Best regards

**Comment by Snorre33** [comment]
Hi

After clearing all filters i get a view entry but incomplete.
When i try to open the entry the console crashes.

![image](https://user-images.githubusercontent.com/45385886/50975114-0f6b3680-14ed-11e9-906f-9fd257da65e7.png)

**Comment by redhook62** [comment]
Hi,

Your User MUST have a username (UPN).
Delete it, and recreate it

Regards

**Comment by Snorre33** [comment]
Hi

The user has a username, but it is not visible in the gui when it is disabled.

![image](https://user-images.githubusercontent.com/45385886/50975578-3d04af80-14ee-11e9-816f-e2f5d13090b6.png)

**Comment by redhook62** [comment]
Hi,

Yes it's good !

Enable-MfaUser ....

For the console close and reopen it.

Regards

**Comment by redhook62** [comment]
In ADDS Attribute msDS-cloudExtensionAttribute18
The value Must be "TRUE" or "FALSE" and not "true".

**Comment by Snorre33** [comment]
Hello

I already tried to reopen the console, the view is still corrupt.

> The value Must be "TRUE" or "FALSE" and not "true".

In AD Attribute editor i can see it in uppercases, only in Powershell it is displayed in this way.

I changed the parameter with "Disable-MFAUsers", i did not change it manually.

Refreshing the GUI takes a really long time when a user is disabled.

In which eventmanager log i should see this issues?

**Comment by redhook62** [comment]
Please delete your user because there's no username, the user name is the key.
If you cannot do that with PowerShell ou MMC, it's because your recorde is wrong.
So remove all the values in ADSIEdit for msDS-cloudExtensionAttribute attributes.

And after create user with PS (Add-MFAUSers), with the console or registering on the fly when login in.

Remember that in ADDS Configuration, adfs service Account must hare read/write rights over all users properties.
If you don't want to write in ADDS, you can use SQL mode configuration.

If you have multiple ADFS Servers, NETBIOS over tcpip must be active on each server lan connection.
And Firewall on both servers must allow ports 137, 138, 139 between both machines

Regards

**Comment by redhook62** [comment]
You can watch in the default eventviewer "Applications"

**Comment by Snorre33** [comment]
Hello

I think it is a display problem in the GUI.
When having the filter "Active users only" enabled i can see the username and email.

![image](https://user-images.githubusercontent.com/45385886/51020806-f069b480-157f-11e9-9500-f8c11ca47acb.png)

After removing all filters i can see entries but no data inside.

![image](https://user-images.githubusercontent.com/45385886/51020812-f65f9580-157f-11e9-8434-05189601f16a.png)

Thank you. Günther

**Comment by redhook62** [comment]
Ok,

But very strange for the MMC, never seen that before.

Regards
