### ISSUE TITLE
users are not getting notified of configuration change

### ISSUE THREAD

**Issue by nathanxa** [neos-sdi/adfsmfa#72]
when users change their configuration, not getting notified about configuration changes.  also, please help us on getting a log file to check the auto email trigger issue. because some times emails are not triggering. no full details in the event log

**Comment by redhook62** [comment]
Hi, @nathanxa 

Several things.
If you think it's the component that is at fault, can you describe exactly how to reproduce it.
Does this happen systematically? for all users? on all types of mails?
In the next version, you will be able to activate the "Delivery Notifications" for emails, either not delivered or simply delayed.
It can be a bad email (existing or not).
Keep in mind that we do not have more details about the errors that occur. We will still add an "Error Status".

Regards

**Comment by nathanxa** [comment]
if I keep system ideal for a few hours (not accessed / no emails triggers),. MFA system disconnects from the SMTP server automatically. so users are failed to get OTP email. again I have to go MFA "Email MF Provider" console and click the "Test". that get fails the first time and sends a test mail in next attempt and start to send OTP emails further. I have tried the SMTP server IP as my internal server, sendgrid, and direct Gmail accounts. the response is the same. Getting event log: Error sending Email (OTP) for user username@upn: Failure sending mail.  could you please add more detailed log file/event log to check the error.

**Comment by redhook62** [comment]
Hi, @nathanxa

We have no more details to provide for the logs, if not the stack and this has really no interest in your case.
I can assure you that a connection is established for each request to send mail, and closed immediately. We do not stay connected.
In your tests, it seems that the test user does not have a UPN, in his profile or in his claims.
Since you use a local mail server, you will certainly find more information in the logs of it. Are ADFS servers allowed to send mails to your server?
Is the login information correct? etc ...

Keep us posted

Regards
