### ISSUE TITLE
need a session expiry for OTP Verification page

### ISSUE THREAD

**Issue by nathanxa** [neos-sdi/adfsmfa#73]
The login session should be expired after some time when no OTP entered. but currently, the session is active infinitely until I close the browser. if I leave the login at OTP page.  it stays on the same page and refreshing the page. can you please add this feature, which makes more secure.

**Comment by redhook62** [comment]
Hi @nathanxa 

Yes, by refreshing the page, the number of tests and the validation time are lost.
Thanks for the information.
Between the 8th and 12th of July we will put a new version correcting this problem.
This release will require the .Net Framework 4.7.2, will allow immediate synchronization between ADFS server (when changing the configuration), as well as a mechanism anti-replay of a TOTP code.
Version will be **2.4.4720.0000**

**Comment by nathanxa** [comment]
if my understanding is correct from your above reply. the attached page in ADFS will get expired after some period of time if no OTP entered.
![image](https://user-images.githubusercontent.com/37096138/60525307-c19cf180-9d0b-11e9-81d5-8f328be40041.png)

**Comment by redhook62** [comment]
Hi, @nathanxa

Yes, in the parameter there is a delay in seconds (300 by default) that applies to all modes of MFA (OTP, MAIL, External, Azure)
This time passed, the session is rejected (taking into account the problem indicated, if currently the browser is refreshed this time is reset to 0)
Otherwise all other security features are provided by ADFS, adfsmfa is only a pluggin, hosted in an ADFS Web Page.

Regards

**Comment by redhook62** [comment]
New Version 2.4.4720.0000
