### ISSUE TITLE
Not working after uninstall 2.0.2 and reinstall 2.4.4720.0001

### ISSUE THREAD

**Issue by pcdiks** [neos-sdi/adfsmfa#80]
This is an additional issue related to https://github.com/neos-sdi/adfsmfa/issues/79

As advised I removed the old software and reinstalled the new software. Then I did a Register-MFASystem and changed the settings through the MMC to match my previous settings.
Now I still get the error with Get-MFAUsers:
```PS C:\Windows\system32> Get-MFAUsers
Get-MFAUsers : The server is not operational.
At line:1 char:1
+ Get-MFAUsers
+ ~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Get-MFAUsers], Exception
    + FullyQualifiedErrorId : 1000,Neos.IdentityServer.MultiFactor.Administration.GetMFAUser
```

Also the Users node in the MMC is not showing any users but does not give an error.

All powershell commands work except the Get-MFAUsers.
Users can logon with MFA with 2.4.4720.0001 after I update the properties to match the previous installation.

**Comment by redhook62** [comment]
Hi @pcdiks 

Thank you, it is perhaps a bug (your are in ADDS Mode).
Don't change something to your registered users !
You can test 2 things : use GetMFAUsers upn@domain.com, and try to Add a new account with ADD-MFAUsers. Some ADDS attributes are mabye with wrong values.
Let us know.

Regards

**Comment by pcdiks** [comment]
- Get-MFAUsers existing.user@upn.com does work.
- Add-MFAUsers -Identity new.user@upn.com -MailAddress new.user@upn.com -Method Code does work.

In the Application eventlog is the following error:
The server is not operational. EventID 5000

**Comment by redhook62** [comment]
OK, wie will look at this problem next week

Regards

**Comment by redhook62** [comment]
@pcdiks 

As we told you before, many things have changed from version 2.0 to better.
You problem is generated by an LDAP error, an ADDS forest can not be joined. 
Multi-forest support is a feature added since.
Your ADDS can not be resolved (DNS), and or the trust relationships are incorrect.
When no parameters are provided, we request ALL ADDS forests. So this is a problem on your side.
However, we will make a modification, to avoid this type of errors ... an explicit entry in the eventlog will be indicated.
Time to redo our battery of tests to have a new version.

**Comment by redhook62** [comment]
Done in 2.4.4720.0002

Regards
