### ISSUE TITLE
Email enrollment wizard not disabled

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#81]
Hi,
We will allow our users to choose if they want to use Email MFA or TOTP MFA. We have the following setup:

**Global parameters - MFA Status:** 
-Mandatory
-Administrative

We want our users to be able to enroll their TOTP and to select default method (but not change their email address), so we also configured:

**Global parameters - Options:** 
-User management options
-User can select default provider

**On MFA Providers - TOTP MFA selected:**
-Active
-Enrollment Wizard

**On MFA Providers - Email MFA selected:**
-Active

When the user select _Access my options after authentication_, they click _Change my configuration options_. There they can now select _Default access method_ and enroll their TOTP via the _Enroll my authentication application_ wizard. 

The problem is that they can also change their MFA email by selecting _Configure options - Personal email address_ and then use the _Enroll my personal email address_ wizard, even though that wizard has been disabled (not selected) under MFA Providers. 

I think that the _Configure option - Personal email address_ should not show up if you have disabled the Email Enrollment Wizard under MFA Providers - Email MFA.

What do you think?

Kind regards,
Andreas

**Comment by redhook62** [comment]
Hi Andreas

Indeed, if the email provider is disabled, normally the access either by "manage my options" or by the wizard for the setting of the email address should not be possible.
I have a client that works with these settings with an older version, 
it must be a bug.

We are going to check that next week

Regards

**Comment by anorstrom** [comment]
Thanks! Just a note. We have the Email Provider enabled but the Email Enrollment Wizard disabled.  

![MFAProvConf](https://user-images.githubusercontent.com/23246525/63087669-09da4100-bf53-11e9-9510-aeb37ace7d82.JPG)

**Comment by redhook62** [comment]
Hi Andreas

I think you can realize this configuration, as previously stated it is in place for one of our customers.

The prerequisites are:
Global Settings - MFA Status:
-Mandatory
-Administrative

Global Settings - Options:
-The user can select the default provider

On the selected MFA - TOTP MFA providers:
-Active
- Registration Assistant

On MFA providers - Selected MFA Email:
-Active

In this case, the user will be able to change the provider at the moment of entering his information MFA by selecting "I do not have the code". both options will be available (TOTP and Email), a check box "remember my choice" is present and checked by default since you have activated the global option "User can select the default provider".

Soon, we will make modifications concerning the module "Manage my Options" see: https://github.com/neos-sdi/adfsmfa/issues/75
And we think in detail for all possible configurations to improve this "historical" module (in versions 1.0)
