### ISSUE TITLE
MFA Spanish Localization

### ISSUE THREAD

**Issue by ImpulsoAngular** [neos-sdi/adfsmfa#88]
Working on the adaptation to the Spanish language and after following the instructions "Localizing adfsmfa", several texts are not shown during the registration process (adfsmfa versión 2.4.4720.2000 in Windows Server 2016).

![Capture1](https://user-images.githubusercontent.com/56454191/68029351-ca8bd880-fc95-11e9-8305-971977c5e10a.PNG)

![Capture2](https://user-images.githubusercontent.com/56454191/68029370-d2e41380-fc95-11e9-8825-915a7412e32f.PNG)

**Comment by redhook62** [comment]
Hi,

We didn't any problem when using external resources sets.
You can follow the instructions in https://github.com/neos-sdi/adfsmfa/wiki/09-Localization#making-your-own-translations.

We just put another version, for another little bug with adfs 2019 theme

See our screens

![image](https://user-images.githubusercontent.com/26826945/68076812-16d03900-fdba-11e9-89f5-6115c83d4d99.png)


![image](https://user-images.githubusercontent.com/26826945/68076816-2a7b9f80-fdba-11e9-8ae0-0e53fd79fdde.png)



![image](https://user-images.githubusercontent.com/26826945/68076821-3c5d4280-fdba-11e9-9945-fb16250f18d4.png)


![image](https://user-images.githubusercontent.com/26826945/68076842-81817480-fdba-11e9-9a1e-302f23c86388.png)

If your problem persists, if you have more details you can re-open this issue

Regards

**Comment by ImpulsoAngular** [comment]
The problem persists. I have repeated the steps and the problem is the same.
Something that caught my attention is that if I copy / paste the files with the language code (example: file_name.es.resources) I get the following error

![image](https://user-images.githubusercontent.com/56454191/68145194-07fd9980-ff14-11e9-947f-2c838b293b5f.png)

If I omit the country code (files_name.resources) it works but with the errors mentioned at the beginning of the thread

**Comment by ImpulsoAngular** [comment]
Forget about the inconvenience. The problem is that apparently the project binaries are not updated on the download page (https://github.com/neos-sdi/adfsmfa/releases). After I downloaded them from the home page (https://github.com/neos-sdi/adfsmfa) everything worked as expected. Sorry, Im not a developer or GitHub man.

**Comment by redhook62** [comment]
Hi @ImpulsoAngular 

Don't Worry, be happy :)
We are also here to give you answers.

No need to be a developer, good will is the best answer.
Hoping that you will fit the interface elements into Spanish correctly translated. 

The initial translation was done with an automatic tool (MS Azure Cognitive Services Translator), and we are sure that no tool with artificial intelligence can compete with humans in all areas.

If you want to share Spanish translations, it would be really cool.

Best Regards

**Comment by ImpulsoAngular** [comment]
Hi @redhook62!

With great pleasure I can cooperate with the translation into Spanish, just be patient. I want to take the opportunity to consult 2 things:
- .Net 4.7.2 is required?
- We have two instances of ADFS where we install ADFSMFA and interestingly, the enrolled users appear in both configurations. Is that the usual behavior?

Thanks!

**Comment by redhook62** [comment]
Hi @ImpulsoAngular 

- Yes .Net 4.7.2 is now required, because the solution is built with fw 4.7.2 (version 2.4.**472**0.3001)

- If you have multiple instances of ADFS (multiple servers for an ADFS Farm), yes it's correct, because all the servers are linked to the same ADDS platform (same forest or approbation relations). in this case you must deploy the component on each ADFS server (not on WAP servers), and you must configure (initialize configuration) on one ADFS Server. if your ADFS farm is using WID (Windows Internal Database) you have to wait for ADFS Synchronization. If your ADFS farm is using SQLServer configuration (SQL Server Database with SQL Server Standard or Enterprise), No need to wait because ADFS Databases are Shared with every ADFS Servers.
- If you have multiple ADFS farms (eg Production and Staging), it's possible if they share the same instances of your ADDS platform. 
Depending of your ADFSMFA configuration (use of ADDS or SQL), in the first case (ADDS option), MFA properties for users ar shared, in this case ADDS replication between differents ADDS domain controllers provide high availabilty. 
In the the case of 2 or more ADDS forests, it' also possible, if these's some trust relationships (Full or one way)between forets

I hope it's clearer for you, but do not hesitate to ask for clarification

Regards
