### ISSUE TITLE
Biometric Authentication

### ISSUE THREAD

**Issue by ImpulsoAngular** [neos-sdi/adfsmfa#94]
Hi!
I am interested in testing biometric authentication, but I am not sure how I should configure it. The idea is to support me on Windows Hello on W10 and ADFS 4.0 with ADFSMFA

**Comment by redhook62** [comment]
Hi @ImpulsoAngular 

To install version 2.5, you must follow the explanations given in the chapter [Upgrade from previous version](https://github.com/neos-sdi/adfsmfa/wiki/03-UpgradeFromPrevious#upgrade-from-previous-versions).
By following this procedure you will not lose any information or settings. 
So, this is where to start.
Remember, make your useful backups for a possible backtrack ! (Adfs Servers and SQL databases if needed)

There are no differences with other past updates, but this is imperative when the binaries version changes (ex: 2.4.x.x to 2.5.x.x).

Apart from the biometric provider, version 2.5 brings a number of fixes, so it is interesting to install this version anyway.

Then, everything will depend on the configuration that you have set up before, in order to configure the biometric part.
For the biometrics part, it is possible to register several keys like Windows Hello (several PCs), Android and Apple phones (very useful and easy to use), and all other devices, tablets, etc.
Up to 10 different keys.

You must refer to the chapter [Biometric Provider Installation](https://github.com/neos-sdi/adfsmfa/wiki/03-UpgradeFromPrevious#configuration-for-the-new-biometric-provider)

If you use the SQL configuration, it is the simplest, a script to add tables will be executed with the command powershell **Upgrade-MFADatabase**
You can also watch the Storage section dedicated to [SQL Server](https://github.com/neos-sdi/adfsmfa/wiki/06-Data-Storage#configuring-sql-mode)

If you are using the Active Directory configuration, it is important to find or create a multivalued attribute to store the different keys for each user.

By default we offer 3 configurations for the ADDS attributes used. knowing that you can decide to replace all or part of it with your own attributes.

- the first configuration, historical ... because exists since the very first version of the component (1.0), is not sensitive to your version of ADDS schema. 
However it's very difficult to find a multivalued attribute available to store biometric credentials. 
We use **otherMailbox** for this attribute, but this is normally used for its initial function. in this case you can change the attribute if you have another suitable one (Multivalued String).
This is the default configuration.

- If you have an ADDS 2016 schema (version 85 or higher), to store the biometic credentials. we chose to use **msDS-KeyCredentialLink** attribute normally dedicated to **Windows Hello For Business** (you can see the exchanges I had with the fido-net-lib project team [here](https://github.com/abergs/fido2-net-lib/issues/137) )
As with the first option, this may not be desirable. it's up to you to judge, this is not the configuration that I personally recommend. but it is perfectly functional.

- The last option, the cleanest in my opinion is to extend the ADDS schema, it will also be the most scalable in the future. 
But, there is still a big drawback, the ADDS schema extensions **are not reversible** (our extension can only be deactivated in the future).
This extension must be deployed on all global catalogs (ADDS Forests) in connection with Adfs via approval relationships.
To implement this change you must apply the LDIF schemes provided after changing the ADDS drill names.
You can find these LDIF files on the Adfs servers in the directory **C:\Program Files\MFA\ADDSTools**
Please refer to the chapter [Active Directory](https://github.com/neos-sdi/adfsmfa/wiki/03-UpgradeFromPrevious#active-directory-configuration).

Once you are there, the installation and update will be complete.

You just have to enter the [Security options for WebAuthN](https://github.com/neos-sdi/adfsmfa/wiki/07-Security#biometrics-security-properties-description)
See also how to make a [Secure configuration](https://github.com/neos-sdi/adfsmfa/wiki/07-Security#create-a-highly-secure-configuration)

Finally, you will need to indicate the properties specific to the [Biometric Provider](https://github.com/neos-sdi/adfsmfa/wiki/08B-MFA-Biometric-Provider#mfa-biometric-provider).
Use the example values provided.

**Now!  it has to be operational.**

contact us, if you still have some questions.

Best regards

**Comment by ImpulsoAngular** [comment]
Sorry for the delay in responding and thanks for the reply @redhook62 . For the next few months I will be testing the biometric authentication functionality, then I will tell you the results.

Greetings and thanks!
